# Generated by Django 4.2.6 on 2023-11-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_alter_consumed_food_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumed',
            name='food_consumed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consumeds', to='counter.food'),
        ),
    ]
