# Generated by Django 4.2.6 on 2023-11-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_alter_consumed_food_consumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumed',
            name='food_consumed',
        ),
        migrations.AddField(
            model_name='food',
            name='food_consumed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Consumeds', to='counter.consumed'),
        ),
    ]
