# Generated by Django 4.2.6 on 2023-11-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_alter_food_food_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_consumed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='counter.consumed'),
        ),
    ]
